/* =====================================================================
   MOTION.JS — scroll reveals, marquee duplication, gallery lightbox.
   Short, understated motion to match the reference site's feel.
   ===================================================================== */
(function motion() {
  const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  const q  = (s, c = document) => c.querySelector(s);
  const qa = (s, c = document) => [...c.querySelectorAll(s)];

  /* ---------- reveal on scroll ---------- */
  const items = qa(".reveal");
  if (reduce) {
    items.forEach((el) => el.classList.add("in"));
  } else if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (!entry.isIntersecting) return;
        entry.target.classList.add("in");
        io.unobserve(entry.target);          // reveal once, then stop watching
      });
    }, { rootMargin: "0px 0px -8% 0px", threshold: 0.08 });
    items.forEach((el) => io.observe(el));
  } else {
    items.forEach((el) => el.classList.add("in"));
  }

  /* ---------- marquee: duplicate the track so the loop is seamless ----
     The CSS animates to -50%, which only lines up if the content is
     present exactly twice. Duplicating here keeps the HTML readable. */
  qa(".marquee-track").forEach((track) => {
    track.innerHTML += track.innerHTML;
  });

  /* =====================================================================
     LIGHTBOX — photos and video, centred, growing out of the tile that
     was clicked.

     The grow is a FLIP: the media is placed at its final centred size,
     then transformed back onto the tile's position and animated to
     nothing. Animating a transform is cheap; animating width and left
     is not, and would judder on a phone.
     ===================================================================== */
  const lb = q("#lightbox");
  if (lb) {
    const lbImg   = q("img", lb);
    const lbVideo = q("video", lb);

    /* Grow the opened media out of the tile it came from. Runs after the
       media has laid out, so the destination rect is real. */
    const growFrom = (originEl, target) => {
      if (reduce || !originEl || !target.animate) return;
      const from = originEl.getBoundingClientRect();
      const to   = target.getBoundingClientRect();
      if (!to.width || !to.height) return;

      const dx = (from.left + from.width  / 2) - (to.left + to.width  / 2);
      const dy = (from.top  + from.height / 2) - (to.top  + to.height / 2);
      const sx = from.width  / to.width;
      const sy = from.height / to.height;

      target.animate([
        { transform: `translate(${dx}px, ${dy}px) scale(${sx}, ${sy})`, opacity: 0.35 },
        { transform: "none", opacity: 1 },
      ], { duration: 420, easing: "cubic-bezier(.22,.61,.36,1)" });
    };

    const show = (el) => { el.hidden = false; };
    const hide = (el) => { el.hidden = true; };

    const openImage = (src, alt, originEl) => {
      hide(lbVideo);
      show(lbImg);
      lbImg.alt = alt || "";
      lb.classList.add("open");
      document.body.classList.add("nav-open");     // lock the page behind

      /* wait for the full size file before measuring, or the grow would
         animate from a zero-height box */
      const run = () => growFrom(originEl, lbImg);
      if (lbImg.src === src && lbImg.complete) { run(); return; }
      lbImg.onload = run;
      lbImg.src = src;
    };

    const openVideo = (src, poster, originEl) => {
      hide(lbImg);
      show(lbVideo);
      lbVideo.poster = poster || "";
      lbVideo.src = src;
      lb.classList.add("open");
      document.body.classList.add("nav-open");
      /* muted is set in the markup as well; both matter, because a
         browser will refuse to autoplay anything with sound */
      lbVideo.muted = true;
      lbVideo.currentTime = 0;
      const p = lbVideo.play();
      if (p && p.catch) p.catch(() => {});          // autoplay may be blocked
      growFrom(originEl, lbVideo);
    };

    const close = () => {
      lb.classList.remove("open");
      document.body.classList.remove("nav-open");
      lbVideo.pause();
      /* drop the source so a closed clip stops using bandwidth */
      lbVideo.removeAttribute("src");
      lbVideo.load();
    };

    /* Delegated on purpose. Tiles are generated by app.js after this file
       runs, so binding to each one here would attach to nothing. */
    const openFrom = (el) => {
      if (!el || el.classList.contains("empty")) return;

      if (el.classList.contains("shot")) {
        const img = q("img", el);
        /* the grid holds a small thumbnail; the full size version is
           only fetched when a photo is actually opened */
        if (img) openImage(img.dataset.full || img.currentSrc || img.src, img.alt, el);
        return;
      }
      if (el.classList.contains("video-card")) {
        openVideo(el.dataset.src, el.dataset.poster, el);
      }
    };

    document.addEventListener("click", (e) => {
      if (!e.target.closest) return;
      openFrom(e.target.closest(".shot, .video-card"));
    });

    /* tiles are focusable, so Enter and Space should open them too */
    document.addEventListener("keydown", (e) => {
      if (e.key !== "Enter" && e.key !== " ") return;
      const el = document.activeElement;
      if (!el || !el.classList) return;
      if (!el.classList.contains("shot") && !el.classList.contains("video-card")) return;
      e.preventDefault();
      openFrom(el);
    });

    /* clicking the backdrop closes; clicking the media itself does not */
    lb.addEventListener("click", (e) => {
      if (e.target !== lbImg && e.target !== lbVideo) close();
    });
    document.addEventListener("keydown", (e) => {
      if (e.key === "Escape" && lb.classList.contains("open")) close();
    });
  }

  /* Reveal helper for content injected after this file runs, such as the
     gallery tiles and video cards. app.js calls it once it has rendered. */
  window.revealItems = (els) => {
    if (!els || !els.length) return;
    if (reduce || !("IntersectionObserver" in window)) {
      els.forEach((el) => el.classList.add("in"));
      return;
    }
    const io = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (!entry.isIntersecting) return;
        entry.target.classList.add("in");
        io.unobserve(entry.target);
      });
    }, { rootMargin: "0px 0px -6% 0px", threshold: 0.05 });
    els.forEach((el) => io.observe(el));
  };

  /* ---------- count-up on the stat strip ---------- */
  const stats = qa("[data-count]");
  if (stats.length && !reduce && "IntersectionObserver" in window) {
    const io2 = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (!entry.isIntersecting) return;
        const el = entry.target;
        const target = parseFloat(el.dataset.count);
        const suffix = el.dataset.suffix || "";
        const dur = 1100;
        const t0 = performance.now();
        (function step(now) {
          const p = Math.min((now - t0) / dur, 1);
          const eased = 1 - Math.pow(1 - p, 3);
          el.textContent = Math.round(target * eased) + suffix;
          if (p < 1) requestAnimationFrame(step);
        })(t0);
        io2.unobserve(el);
      });
    }, { threshold: 0.5 });
    stats.forEach((el) => io2.observe(el));
  }
})();
